# packages in environment at /home/user/anaconda3/envs/:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
_openmp_mutex             4.5                       2_gnu    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
deepspeed                 0.5.9                    pypi_0    pypi
descriptastorus           2.5.0.20                 pypi_0    pypi
django                    4.2.6                    pypi_0    pypi
djangorestframework       3.14.0                   pypi_0    pypi
libzlib                   1.2.13               h166bdaf_4    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
mpmath                    1.3.0                    pypi_0    pypi
dgl                       0.6.0                    pypi_0    pypi
dgl-cuda11.6              0.9.1post1               py39_0    dglteam
dgllife                   0.3.2                    pypi_0    pypi
deeppurpose               0.1.5                    pypi_0    pypi
matplotlib-base           3.6.2            py39hf9fd14e_0    conda-forge
matplotlib-inline         0.1.6                    pypi_0    pypi
numpy                     1.24.4                   pypi_0    pypi
numpydoc                  1.5.0                    pypi_0    pypi
nvidia-cublas-cu11        11.10.3.66               pypi_0    pypi
nvidia-cuda-cupti-cu11    11.7.101                 pypi_0    pypi
nvidia-cuda-nvrtc-cu11    11.7.99                  pypi_0    pypi
nvidia-cuda-runtime-cu11  11.7.99                  pypi_0    pypi
nvidia-cudnn-cu11         8.5.0.96                 pypi_0    pypi
nvidia-cufft-cu11         10.9.0.58                pypi_0    pypi
nvidia-curand-cu11        10.2.10.91               pypi_0    pypi
nvidia-cusolver-cu11      11.4.0.1                 pypi_0    pypi
nvidia-cusparse-cu11      11.7.4.91                pypi_0    pypi
nvidia-nccl-cu11          2.14.3                   pypi_0    pypi
nvidia-nvtx-cu11          11.7.91                  pypi_0    pypi
openbabel                 3.1.1            py39h80c93ca_5    conda-forge
packaging                 22.0               pyhd8ed1ab_0    conda-forge
pip                       23.3.2                   pypi_0    pypi
python                    3.9.15          hba424b6_0_cpython    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-slugify            5.0.2                    pypi_0    pypi
python_abi                3.9                      3_cp39    conda-forge
pytorch-lightning         1.8.6                    pypi_0    pypi
pytorch-pretrained-bert   0.6.2                    pypi_0    pypi
pytorch-transformers      1.1.0                    pypi_0    pypi
pandas                    1.5.2            py39h4661b88_0    conda-forge
pandas-flavor             0.5.0                    pypi_0    pypi
rdkit                     2022.9.5                 pypi_0    pypi
readline                  8.1.2                h0f457ee_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
scikit-learn              0.24.2                   pypi_0    pypi
seaborn                   0.12.1                   pypi_0    pypi
scipy                     1.9.3                    pypi_0    pypi
tqdm                      4.64.1                   pypi_0    pypi
torch                     2.0.1                    pypi_0    pypi
torch-cluster             1.6.1+pt20cu117          pypi_0    pypi
torch-geometric           2.3.1                    pypi_0    pypi
torch-scatter             2.1.1+pt20cu117          pypi_0    pypi
torch-sparse              0.6.17+pt20cu117          pypi_0    pypi
torch-spline-conv         1.2.2+pt20cu117          pypi_0    pypi
torchaudio                2.0.2                    pypi_0    pypi
torchdata                 0.7.1                    pypi_0    pypi
torchmetrics              0.11.4                   pypi_0    pypi
torchvision               0.15.2                   pypi_0    pypi
transformers              4.35.2                   pypi_0    pypi
urllib3                   1.26.13                  pypi_0    pypi
wget                      3.2                      pypi_0    pypi
wheel                     0.41.0                   pypi_0    pypi
xgboost                   2.0.0                    pypi_0    pypi
xz                        5.2.6                h166bdaf_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
yarl                      1.9.2                    pypi_0    pypi
zipp                      3.16.2                   pypi_0    pypi